# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               <center><img src="https://raw.githubusercontent.com/baselguys/baselguys.github.io/master/public/basel guys logo_small.png" height=120>  </img> </center> <center>Basel Guys</center>
tagline:             <center>'smart guys on risky problems'</center>
description:         '' 
baseurl:             ''

