# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               <img src="https://raw.githubusercontent.com/baselguys/baselguys.github.io/master/public/basel_guys_logo.png" height=60>  </img> Basel Guys
tagline:             'smart guys on risky problems'
description:         '<img src="https://raw.githubusercontent.com/baselguys/baselguys.github.io/master/public/basel_guys_logo.png" height=60>  </img>' 
baseurl:             ''

